/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module input_capture_3 (
    input clk,
    input rst,
    output reg [5:0] button_col,
    input [4:0] button_row,
    output reg [1:0] guessled,
    output reg [4:0] somechar
  );
  
  
  
  
  wire [5-1:0] M_bm_char;
  reg [6-1:0] M_bm_button_col;
  reg [5-1:0] M_bm_button_row;
  buttonmapping_7 bm (
    .button_col(M_bm_button_col),
    .button_row(M_bm_button_row),
    .char(M_bm_char)
  );
  
  always @* begin
    somechar = M_bm_char;
    guessled = 2'h3;
    M_bm_button_col = 6'h02;
    M_bm_button_row = button_row;
    if (button_row == 1'h0) begin
      guessled = 2'h0;
    end
    button_col = 6'h02;
  end
endmodule
