/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module settings_5 (
    input clk,
    input rst,
    input [4:0] button,
    output reg [3:0] speed_disp,
    output reg [3:0] length_disp,
    output reg [0:0] start,
    output reg [25:0] increment
  );
  
  
  
  reg [25:0] M_incr_d, M_incr_q = 1'h0;
  reg [3:0] M_speed_d, M_speed_q = 1'h0;
  reg [3:0] M_length_d, M_length_q = 1'h0;
  
  always @* begin
    M_speed_d = M_speed_q;
    M_length_d = M_length_q;
    M_incr_d = M_incr_q;
    
    M_incr_d = 26'h2faf080;
    increment = M_incr_q;
    speed_disp = M_speed_q;
    length_disp = M_length_q;
    M_speed_d = 2'h3;
    M_length_d = 2'h3;
    start = 1'h0;
    
    case (button)
      5'h02: begin
        if (M_incr_q < 26'h0000100 && M_speed_q < 4'h9) begin
          M_incr_d = M_incr_q << 1'h1;
          M_speed_d = M_speed_q + 1'h1;
        end
      end
      5'h01: begin
        if (M_incr_q > 26'h0000001 && M_speed_q > 4'h0) begin
          M_incr_d = M_incr_q >> 1'h1;
          M_speed_d = M_speed_q - 1'h1;
        end
      end
      5'h08: begin
        if (M_length_q < 4'h9) begin
          M_length_d = M_length_q + 1'h1;
        end
      end
      5'h10: begin
        if (M_length_q > 4'h0) begin
          M_length_d = M_length_q - 1'h1;
        end
      end
      5'h04: begin
        start = 1'h1;
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_incr_q <= M_incr_d;
    M_speed_q <= M_speed_d;
    M_length_q <= M_length_d;
  end
  
endmodule
